{{- if empty .Values.credsSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backup-zen.backupCredsSecretName" . }}
  labels: {{ include "backup-zen.labels" . | nindent 4 }}
  namespace: {{ include "backup-zen.namespace" . }}
data:
  {{- if eq .Values.credentialType "adminUser" }}
  USERNAME: {{ default "root" .Values.adminUser.username | b64enc }}
  PASSWORD: {{ default "root" .Values.adminUser.password | b64enc }}
  {{ end -}}
  {{- if eq .Values.credentialType "oneByOne" }}
  creds.json: {{ default "[]" .Values.oneByOne.creds | toJson | b64enc }}
  {{- end }}
type: Opaque

{{ end -}}
